name: Docker Image CI

on:
  push:
    branches: [ nontested ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: docker/build-push-action@v1
      - name: Build docker image
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: anodev/image-background-remove-tool
          tags: latest
