name: Docker Image CI

on:
  push:
    branches: [ nontested ]
  pull_request:
    branches: [ nontested ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag image-background-remove-tool:$(date +%s)
    - uses: docker/build-push-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: anodev/image-background-remove-tool
          tags: latest
